name: 'Delete OSS'
description: 'Delete all files in buckets of aliyun OSS '
inputs:
  region:
    required: true
  key-id:
    required: true
  key-secret:
    required: true
  bucket:
    required: true

runs:
  using: 'node16'
  main: 'index.js'